version: "3.9"
services:
  playqd-service-discovery:
    image: "playqd-service-discovery:1.0.0"
    build: .
    restart: always
    ports:
      - "9915:9915"
    volumes:
      - ./docker/playqd-service-discovery:/app/playqd/config
  playqd-media-library:
    image: "playqd-media-library:0.0.1"
    build: .
    restart: always
    ports:
      - "8015:8015"
    volumes:
      - F:/Media/Music:/media/music
      - C:/Users/gregory.kosik/.playqd:/.playqd
    env_file:
      - .env
    environment:
      - spring.datasource.password=${playqd_media_library_db_pwd}