version: "3.9"
services:
  prometheus:
    image: "prom/prometheus"
    build: .
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  playqd-service-discovery:
    image: "playqd-service-discovery:1.0.0"
    build: .
    restart: always
    ports:
      - "9915:9915"
    volumes:
      - ./docker/playqd-service-discovery:/app/playqd/config
  playqd-media-library:
    image: "playqd-media-library:0.0.2"
    build: .
    restart: always
    ports:
      - "8015:8015"
    volumes:
      - ${hostMusicDir}:/media/music
      - ${hostWorkingDir}:/.playqd
      - ${hostWinampPlaylistsDir}:/media/playlists/winamp
    env_file:
      - .env
    environment:
      - eureka.instance.hostname=${eurekaInstanceHostname}
      - spring.datasource.password=${dbPwd}